### ISSUE TITLE
To-do!

### ISSUE THREAD

**Issue by shamdasani** [mguida22/Connections#1]
- [x] QR codes, server side
- [x] camera + scanner in react native
- [x] authentication
- [ ] social follow functions
- [ ] make FB profile pic the background of QR code
- [x] get built Xcode IPA (upload on branch)

**Comment by mguida22** [comment]
Let's make the QR code store info like this:

```
{
  "fb": "fb_id",
  "twitter: "twitter_id"
  ...
}
```
For each social media they select, it'll add to the JSON and we can use that to add them on the person who scans the QR code's phone

**Comment by samayshamdasani** [comment]
Objectives before we sleep:
- Complete the functioning app (make it just work)

When we wake up:
- XCode bug fixing and IPA file
- website counter?

**Comment by mguida22** [comment]
![simulator screen shot jan 22 2017 7 31 50 am](https://cloud.githubusercontent.com/assets/9451227/22182585/b801412a-e076-11e6-88e3-b3343117f803.png)
![simulator screen shot jan 22 2017 7 36 30 am](https://cloud.githubusercontent.com/assets/9451227/22182586/baff0934-e076-11e6-8ea9-913e29fbb3c1.png)
![simulator screen shot jan 22 2017 7 45 52 am](https://cloud.githubusercontent.com/assets/9451227/22182589/d244636e-e076-11e6-8c9f-180e599aefd1.png)
![puppy_qrcode](https://cloud.githubusercontent.com/assets/9451227/22182668/3a301516-e079-11e6-868c-d81a044c66be.png)
![me_qrcode](https://cloud.githubusercontent.com/assets/9451227/22182679/659d9ee4-e079-11e6-8274-6ced2ae64dd9.png)
